version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 421010732768.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 421010732768.dkr.ecr.us-east-1.amazonaws.com/myapp:latest .
      - echo Tagging the Docker image with CODEBUILD_BUILD_ID...
      - docker tag 421010732768.dkr.ecr.us-east-1.amazonaws.com/myapp:latest 421010732768.dkr.ecr.us-east-1.amazonaws.com/myapp:$CODEBUILD_BUILD_ID
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to Amazon ECR...
      - docker push 421010732768.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
      - docker push 421010732768.dkr.ecr.us-east-1.amazonaws.com/myapp:$CODEBUILD_BUILD_ID
artifacts:
  files: imagedefinitions.json
